engineering_hours_end_status: Code Review
engineering_hours_excluded_statuses:
- Blocked
engineering_hours_start_status: In Progress
jira:
  base_url: https://your-org.atlassian.net
  email: your-email@omio.com
  field_ids:
    eng_hours: customfield_18466
    tpd_bu: customfield_17924
    work_stream: customfield_18837
  project_key: ACTIN
mapping_rules:
  tpd_bu:
    B2B: []
    B2C: []
    Global Expansion: []
    O4B: []
    Omio.AI: []
    Rome2Rio: []
  work_stream:
    Operational: []
    Product: []
    Tech Meta Backlog: []
office_hours:
  end: '18:00'
  exclude_weekends: true
  start: 09:00
  timezone: Europe/Berlin
sync:
  auto_write_to_jira: false
  interval_minutes: 60
ticket_filter:
  mode: last_x_months
  months: 6
