[pytest]
testpaths = .
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts =
    --cov=.
    --cov-report=term-missing
    --cov-report=html:htmlcov
    --cov-branch
    --cov-fail-under=90
    --ignore=.venv
    -v
